import { RecipeIngredient } from './recipeingredient';
import { Financial } from './financial';
import { User } from '../user';
import { Unit } from './unit';
import { RecipeLabelAllergen } from './RecipeLabelAllergen';
import { RecipeLabelIngredient } from './RecipeLabelIngredient';

export class RecipeLabel {
	id?: number;
	weight: number;
	portion: number;
	measure: string;
	servingsPerContainers: number;
	gluten: boolean;
	lactose: boolean;
	kcal: boolean = true;
	carbohydrates: boolean = true;
	fibers: boolean = true;
	protein: boolean = true;
	totalFat: boolean = true;
	saturatedFat: boolean = true;
	transFat: boolean = true;
	sodium: boolean = true;
	cholesterol: boolean;
	monounsatured: boolean;
	polyunsatured: boolean;
	calcium: boolean;
	magnesium: boolean;
	manganese: boolean;
	phosphorus: boolean;
	iron: boolean;
	potassium: boolean;
	copper: boolean;
	zinc: boolean;
	retinol: boolean;
	vitaminARAE: boolean;
	vitaminD: boolean;
	thiamine: boolean;
	riboflavin: boolean;
	pyridoxine: boolean;
	niacin: boolean;
	vitaminB6: boolean;
	vitaminB12: boolean;
	vitaminC: boolean;
	lipids: boolean;
	allergens: RecipeLabelAllergen[];
	ingredients: RecipeLabelIngredient[] = [];
	totalSugars: boolean;
	addedSugars: boolean;
}
